### ISSUE TITLE
Uninstall pretty_errors

### ISSUE THREAD

**Issue by johnvonneumann36** [onelivesleft/PrettyErrors#12]
Hi,

When I'm trying to uninstall pretty_errors after using:
`python -m pretty_errors`

And the python can't run normally, and got this:
Python can't import pretty_errors.

**Comment by onelivesleft** [comment]
Yeah, the call to import will be left behind.  I'll see if there's a hook to run some code when you uninstall a module, but I am not optimistic: they deliberately don't give you one when you install (which is why you have to run `python -m pretty_errors` to add it to your startup, instead of just giving you the option automatically when you do the `python -m pip install pretty_errors`).

Meanwhile, the fix is to install pretty errors again, run the command you listed to display where it has been added to your startup, and either delete the file (if it is a `.pth`), or edit it, removing the `pretty_errors` section.

**Comment by onelivesleft** [comment]
v1.2.8 addresses this issue by adding a `clean` function to the module when it is run directly, and by changing the generated import in *customize.py files so that it outputs the path of the file the user needs to edit.
