### ISSUE TITLE
Implementation into pytest

### ISSUE THREAD

**Issue by jackblk** [onelivesleft/PrettyErrors#30]
Hello there,

Thanks for creating this awesome lib :). I've been using it for few hours and I just cannot get it to work with `pytest`.

Example code:
```python
import pretty_errors
pretty_errors.replace_stderr()
def test_abc():
    assert 1==1
    a = ''
    print("ok")
    b = a[0]
```
Terminal output:
![image](https://user-images.githubusercontent.com/12843654/102882542-16dd3d80-4481-11eb-8add-87234bafec91.png)

Is there anyway to make it work with pytest? Thanks a lot :).

**Comment by onelivesleft** [comment]
Looking at what pytest is, there's no way to integrate the two: pytest is taking over the output and reformatting it itself - not only is it adding color, it's completely re-arranging what is displayed.  First it grabs stderr, preventing `pretty-errors` from doing so, and then it drastically alters what is displayed.  I see you tried `replace_stderr`: normally this is what to do, but it works by checking what is output to stderr, and when it sees text that matches the standard format of an exception it grabs it and infers from it what the exception is.  Because `pytest` has completely changed the output of the exception, `pretty-errors` can't tell what the exception is.

These are two packages which both want to completely re-write the output of python programs: they're fundamentally opposed, so I'm not sure if they could ever be meshed together.  HOWEVER, reading the pytest docs here: 

https://docs.pytest.org/en/stable/usage.html#modifying-python-traceback-printing

it looks like you could try running it with `pytest --tb=native` : then `pretty-errors` might be able to see the exception when it's in `replace_stderr` mode.  I can't guarantee it'll look good though, even if it works!

**Comment by jackblk** [comment]
Thanks for the reply!

I've tried `--tb=native` but it does not work. It will output just like the native traceback, but it does not work with pretty_errors, with or without `replace_stderr`.

Next step might be that we write a hook for pytest to add new option. Maybe `--tb=pretty_errors`. I will look into that. Thanks again for very fast response 👍

**Comment by jackblk** [comment]
Coming back here because I found a work around where I think it's enough for me in Pytest: install https://github.com/willmcgugan/rich

Not exactly the same as pretty_errors, but we will get to see better color scheme than Pytest, and that's enough for me for now :).
